### ISSUE TITLE
Will the citrus video data set be provided in the future?

### ISSUE THREAD

**Issue by RanJie-1924405079** [robotic-vision-lab/CitDet-A-Benchmark-Dataset-For-Citrus-Fruit-Detection#1]
For fruit yield estimation research.

**Comment by jjames71396** [comment]
There is no associated video data for this work. Instead, we perform yield estimation via detection using dual-sided imagery. All images and fruit counts used for yield estimation are available on the USDA [agdatacommons](https://agdatacommons.nal.usda.gov/articles/dataset/Data_from_CitDet_a_benchmark_dataset_for_citrus_fruit_detection/24669006?file=43378257).

**Comment by RanJie-1924405079** [comment]
> There is no associated video data for this work. Instead, we perform yield estimation via detection using dual-sided imagery. All images and fruit counts used for yield estimation are available on the USDA [agdatacommons](https://agdatacommons.nal.usda.gov/articles/dataset/Data_from_CitDet_a_benchmark_dataset_for_citrus_fruit_detection/24669006?file=43378257).
Thank you for your answer. I would also like to ask if the citrus re-annotation data can be shared after the expansion to 5,211 pictures?
