### ISSUE TITLE
How to get segmentation information

### ISSUE THREAD

**Issue by mitsuki05** [robotic-vision-lab/CitDet-A-Benchmark-Dataset-For-Citrus-Fruit-Detection#3]
How can I get a segmented image instead of a bounding box?
It looks like there's nothing inside the segmentation in the json file provided.

_annotations.coco.json
{"id": 10092, "image_id": 145, "category_id": 1, "bbox": [813, 2383, 63, 48], "area": 3024, "segmentation": [], "iscrowd": 0}

**Comment by jjames71396** [comment]
Currently, only bounding box annotations for detection and psuedo masks for semantic segmentation are available. We plan to release instance masks in the near future.

**Comment by mitsuki05** [comment]
Thanks for the reply.
